# Generated by Django 5.2.15 on 2026-06-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet')], default='mobile', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('app_manager', 'App Manager'), ('normal_user', 'Normal User')], default='normal_user', max_length=20),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='support_email',
            field=models.EmailField(default='britsyncuk@gmail.com', max_length=254),
        ),
    ]
