# Generated by Django 5.2.15 on 2026-06-24 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_screenshot_type_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_emoji',
            field=models.CharField(blank=True, help_text='Fallback emoji if no icon image', max_length=10),
        ),
        migrations.AddField(
            model_name='download',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='category_icons/'),
        ),
    ]
