# Generated by Django 5.2.15 on 2026-06-25 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='force_update',
            field=models.BooleanField(default=False, help_text='Force users to update to this version'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='is_latest',
            field=models.BooleanField(default=False, help_text='Currently the latest published version'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='version_code',
            field=models.IntegerField(default=1, help_text='Numeric version code for comparison (e.g. 3 for v1.0.3)'),
        ),
        migrations.AlterField(
            model_name='app',
            name='package_name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('contact', 'New Contact Message'), ('app_upload', 'App Uploaded'), ('app_published', 'App Published'), ('version_upload', 'Version Uploaded')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this token (e.g. "GitHub Actions - MyApp")', max_length=100)),
                ('package_name', models.CharField(blank=True, default='', help_text='If set, this token can only upload releases for this package name (e.g. com.ascentra.crm). Leave empty for unrestricted access.', max_length=200)),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(blank=True, default='', max_length=100)),
                ('package_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('version_code', models.IntegerField(default=1)),
                ('force_update', models.BooleanField(default=False)),
                ('apk_path', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='store.apitoken')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Audit Log',
                'verbose_name_plural': 'Upload Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
