# Generated by Django 5.2.15 on 2026-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_appversion_force_update_appversion_is_latest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='age_rating',
            field=models.CharField(choices=[('all', 'All Ages'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='all', max_length=4),
        ),
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD (only for paid apps)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='price_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4),
        ),
    ]
