# Generated by Django 5.2.15 on 2026-06-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_app_age_rating_app_price_app_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD — US Dollar'), ('PKR', 'PKR — Pakistani Rupee'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('INR', 'INR — Indian Rupee'), ('AED', 'AED — UAE Dirham'), ('SAR', 'SAR — Saudi Riyal')], default='USD', help_text='Currency for paid apps', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (only for paid apps)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='about_title',
            field=models.CharField(default='About BritStore', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='hero_title',
            field=models.CharField(default='Discover BritStore Apps', max_length=200),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='site_name',
            field=models.CharField(default='BritStore', max_length=100),
        ),
    ]
