# Generated by Django 4.2.16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_androidfingerprintdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
