# Generated by Django 5.2.15 on 2026-07-27 14:27

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rating_comment_rating_updated_at_alter_rating_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="apk_file",
            field=models.FileField(
                blank=True, default="", upload_to=store.models.app_apk_path
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apps",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="full_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="app",
            name="icon",
            field=models.ImageField(
                blank=True, default="", upload_to=store.models.app_icon_path
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="short_description",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
