# Generated by Django 5.2.15 on 2026-10-07 02:54

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_make_ci_upload_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="exe_file",
            field=models.FileField(
                blank=True, default="", upload_to=store.models.app_exe_path
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="platform",
            field=models.CharField(
                choices=[("android", "Android"), ("desktop", "Desktop (Windows)")],
                default="android",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="app",
            name="windows_version",
            field=models.CharField(blank=True, default="Windows 10+", max_length=50),
        ),
        migrations.AddField(
            model_name="appversion",
            name="exe_file",
            field=models.FileField(
                blank=True, default="", upload_to=store.models.version_exe_path
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD - US Dollar"),
                    ("PKR", "PKR - Pakistani Rupee"),
                    ("EUR", "EUR - Euro"),
                    ("GBP", "GBP - British Pound"),
                    ("INR", "INR - Indian Rupee"),
                    ("AED", "AED - UAE Dirham"),
                    ("SAR", "SAR - Saudi Riyal"),
                ],
                default="USD",
                help_text="Currency for paid apps",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="package_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="apk_file",
            field=models.FileField(
                blank=True, default="", upload_to=store.models.version_apk_path
            ),
        ),
    ]
